// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANoCcbiGMfSNwvwTcz6IwJHArHIONhgBU',
    appId: '1:796721500661:web:506d82ad2f36f71b4dd0bc',
    messagingSenderId: '796721500661',
    projectId: 'project-p-d04ab',
    authDomain: 'project-p-d04ab.firebaseapp.com',
    storageBucket: 'project-p-d04ab.appspot.com',
    measurementId: 'G-78SZ7J32XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUiCYio-HWOzl9zjsMXyb-dwj5Ut4Ots8',
    appId: '1:796721500661:android:b0543eac4437bcdb4dd0bc',
    messagingSenderId: '796721500661',
    projectId: 'project-p-d04ab',
    storageBucket: 'project-p-d04ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClc2ESoEZMlhydbjoWUuQ6xKHN7WF1_w0',
    appId: '1:796721500661:ios:3139d96c88f146dc4dd0bc',
    messagingSenderId: '796721500661',
    projectId: 'project-p-d04ab',
    storageBucket: 'project-p-d04ab.appspot.com',
    androidClientId: '796721500661-958nbfpa81qtqkvt4cl6haakhpdh7ovp.apps.googleusercontent.com',
    iosClientId: '796721500661-kalv7qp36u1llqvs94uj51oje9k1r23r.apps.googleusercontent.com',
    iosBundleId: 'com.albert.p',
  );
}
